CREATE TABLE activities (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    type VARCHAR(30) NOT NULL CHECK (type IN ('PAYMENT_RECEIVED', 'STOCK_DISTRIBUTED', 'STOCK_RECEIVED', 'RESELLER_SALE')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);